ALTER TABLE content_queue
  ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS calendar_id UUID,
  ADD COLUMN IF NOT EXISTS notes TEXT;
